version: '3.8'

services:
  web:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - .:/app
      - app-data:/app/data  # Persisting data in this directory
    ports:
      - "8080:8080"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 8080
    command: flask run

volumes:
  app-data:
