apiVersion: apps/v1
kind: Deployment
metadata:
  name: place-backend-app
spec:
  selector:
    matchLabels:
      app: place-backend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: place-backend-app
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: place-backend
          image: {{ print .Values.images.backend .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /data
              name: place-data-volume
      imagePullSecrets:
      - name: github-registry
      volumes:
        - name: place-data-volume
          persistentVolumeClaim:
            claimName: place-data-pvc