apiVersion: v1
kind: Service
metadata:
  name: place-backend-service
spec:
  selector:
    app: place-backend-app
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: place-backend-app
spec:
  selector:
    matchLabels:
      app: place-backend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: place-backend-app
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
        - name: place-backend
          image: {{ print .Values.images.backend .Values.tag }}
          imagePullPolicy: Always
          envFrom:
          ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: github-registry
