apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: place-ingress
  annotations:
    nginx.ingress.kubernetes.io/from-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 12m
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "server: hide";
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: place-tls-cert-prod
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: place-backend-service
            port:
              number: 8080
